name: queue_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #infraestructure:

  # di
  get_it: ^7.6.4

  # state manager
  flutter_bloc: ^8.1.3

  # hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # rest api
  dio: ^5.4.0
  dio_retry_plus: ^2.0.5

  # alice = chuck
  chuck_interceptor: ^2.0.4

  #Option, Either,
  dartz: ^0.10.1

  #code generator for data-classes/unions/pattern-matching/cloning
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1

  #built_value:
  built_value: ^8.8.1

#  connectivity_plus: ^5.0.2

  #localization:
  easy_localization: ^3.0.3



  # presentation:

  flutter_screenutil: ^5.9.0

  # svg
  flutter_svg: ^2.0.8

  # cached image
  cached_network_image: ^3.3.0

  keyboard_dismisser: ^3.0.0

  flutter_native_splash: ^2.3.8





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  built_value_generator: ^8.8.1


flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/icons/img/
    - assets/icons/svg/
    - assets/translations/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #